version: "3"
services:
  hqt_app:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    entrypoint: ["npm", "start"]
    volumes:
      - ./src:/app/src
      - .env:/app/.env
